#!/usr/bin/env bash
# Anyray setup — generates every secret the stack needs.
# Default: writes .env for docker compose.
# With --k8s: writes anyray-secrets.yaml + my-values.yaml for Helm.
# With --connect <adt_token>: also links this deployment to Anyray Cloud
#   (token from https://app.anyray.ai). Safe to re-run to reconnect.
# With --upstream <url>: point Anyray at an existing OpenAI-compatible gateway
#   (LiteLLM, OpenRouter, …) so clients send plain requests with NO per-request
#   x-anyray-config header. Safe to re-run to change the upstream.
# Idempotent: never overwrites existing secrets; --connect (re)writes only the
# Anyray Cloud connect vars and --upstream only the upstream vars. Flags: --host
# <h> --k8s --connect <adt_token> --gateway-url <url> --upstream <url>.
# (--control-plane <url> is DEV/INTERNAL ONLY: the vendor host is pinned +
# defaulted in the gateway image, so a normal connect never needs it; passing it
# only does anything for an internal/dev gateway build via the unsafe override
# below.)
set -euo pipefail

HOST=""
K8S=0
CONNECT_TOKEN=""
CONTROL_PLANE="https://app.anyray.ai"
GATEWAY_URL=""
UPSTREAM_URL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --host) HOST="${2:?--host needs a value}"; shift 2 ;;
    --k8s)  K8S=1; shift ;;
    --connect)       CONNECT_TOKEN="${2:?--connect needs a deployment token (adt_…)}"; shift 2 ;;
    --control-plane) CONTROL_PLANE="${2:?--control-plane needs a URL}"; shift 2 ;;
    --gateway-url)   GATEWAY_URL="${2:?--gateway-url needs a URL}"; shift 2 ;;
    --upstream)      UPSTREAM_URL="${2:?--upstream needs a URL (e.g. http://host.docker.internal:4000)}"; shift 2 ;;
    *) echo "✗ unknown flag: $1 (supported: --host <hostname-or-ip> --k8s --connect <adt_token> --control-plane <url> --gateway-url <url> --upstream <url>)" >&2; exit 1 ;;
  esac
done

if [ "$K8S" -eq 1 ] && [ -n "$UPSTREAM_URL" ]; then
  echo "✗ --upstream supports the docker compose flow only (set upstream.url in my-values.yaml for Helm)" >&2
  exit 1
fi

command -v openssl >/dev/null 2>&1 || { echo "✗ openssl not found" >&2; exit 1; }

if [ "$K8S" -eq 0 ]; then
  command -v docker >/dev/null 2>&1 || { echo "✗ docker not found — https://docs.docker.com/engine/install/" >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { echo "✗ docker compose v2 not found — https://docs.docker.com/compose/install/" >&2; exit 1; }
fi

if [ -z "$HOST" ]; then
  HOST="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  # macOS: hostname has no -I — fall back to the primary interface address so
  # the gateway URL shown to developers is reachable, not "localhost".
  [ -n "$HOST" ] || HOST="$(ipconfig getifaddr en0 2>/dev/null || true)"
  [ -n "$HOST" ] || HOST=localhost
fi

hex() { openssl rand -hex "$1"; }
b64() { openssl rand -base64 32; }
b64enc() { printf '%s' "$1" | base64 | tr -d '\n'; }

# ── Docker Compose mode ──────────────────────────────────────────────────────
if [ "$K8S" -eq 0 ]; then
  if [ -f .env ]; then
    echo "✓ .env already exists — leaving it untouched (delete it to regenerate)"
    grep '^# Console:' .env | sed 's/^# //' || true
    [ -n "$CONNECT_TOKEN" ] || [ -n "$UPSTREAM_URL" ] || exit 0
  else
    if [ -z "${DOCKER_HOST:-}" ] && command -v lsof >/dev/null 2>&1; then
      for p in 3000 8787; do
        if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
          echo "⚠ port $p is already in use on this machine — the stack may fail to start"
        fi
      done
    fi

    ADMIN_TOKEN="ar-adm-$(hex 16)"
    LF_PUBLIC_KEY="pk-lf-$(hex 16)"
    LF_SECRET_KEY="sk-lf-$(hex 16)"

    cat > .env <<EOF
# Generated by setup.sh — do not commit. Delete this file and re-run to rotate.
# Console: http://${HOST}:3000

# Gateway ↔ observability (the two pairs must match)
ANYRAY_OBSERVABILITY_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_OBSERVABILITY_SECRET_KEY=${LF_SECRET_KEY}
ANYRAY_INIT_PROJECT_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_INIT_PROJECT_SECRET_KEY=${LF_SECRET_KEY}

# Gateway ↔ optimizer shared secret
ANYRAY_OPTIMIZER_TOKEN=$(hex 32)

# Content privacy (AES-256-GCM at rest; encrypted is the default mode)
ANYRAY_CONTENT_KEY=$(hex 32)
ANYRAY_CONTENT_MODE=encrypted
ANYRAY_ALLOW_PLAINTEXT=false

# Single admin key — gates the console and all /admin APIs
ANYRAY_ADMIN_TOKEN=${ADMIN_TOKEN}

# Observability backend
NEXTAUTH_SECRET=$(b64)
SALT=$(b64)
ENCRYPTION_KEY=$(hex 32)
NEXTAUTH_URL=http://${HOST}:3000
TELEMETRY_ENABLED=false
ANYRAY_INIT_ORG_ID=anyray
ANYRAY_INIT_ORG_NAME=Anyray
ANYRAY_INIT_PROJECT_ID=anyray-gateway
ANYRAY_INIT_PROJECT_NAME=Anyray Gateway
ANYRAY_INIT_USER_EMAIL=admin@anyray.local
ANYRAY_INIT_USER_NAME=Admin
ANYRAY_INIT_USER_PASSWORD=$(hex 16)

# Datastores
POSTGRES_PASSWORD=$(hex 16)
CLICKHOUSE_PASSWORD=$(hex 16)
REDIS_AUTH=$(hex 16)
MINIO_ROOT_PASSWORD=$(hex 16)
EOF
    chmod 600 .env

    echo "✓ Secrets generated → .env"
    echo ""
    echo "  Console:   http://${HOST}:3000"
    echo "  Admin key: ${ADMIN_TOKEN}   (also stored in .env as ANYRAY_ADMIN_TOKEN)"
    echo "  Gateway:   http://${HOST}:8787"
    [ -n "$CONNECT_TOKEN" ] || { echo ""; echo "  Next:      docker compose up -d"; }
  fi

  # ── Anyray Cloud connect (--connect) ───────────────────────────────────────
  # (Re)writes only the connect vars below — every other line of .env is kept.
  if [ -n "$CONNECT_TOKEN" ]; then
    case "$CONNECT_TOKEN" in
      adt_*) : ;;
      *) echo "⚠ deployment token does not start with adt_ — double-check it against app.anyray.ai" ;;
    esac

    # The vendor's Ed25519 verify key and the control-plane host are PINNED in
    # the gateway image — they are no longer fetched or written here. That is
    # what makes the billing kill-switch tamper-resistant: re-pointing the URL
    # at a look-alike control plane gets nowhere, because the stock image won't
    # phone home to a non-pinned host and verifies leases only against the
    # baked-in key. So a custom --control-plane only works with an INTERNAL/DEV
    # gateway build, gated behind the unsafe override below.
    CANONICAL_CP="https://app.anyray.ai"
    CP_NORM="${CONTROL_PLANE%/}"

    # Pseudonym salt: generated locally and NEVER sent anywhere — it
    # pseudonymizes employee identifiers before metering. Reconnecting keeps
    # the existing salt so usage history stays attributable.
    PSEUDONYM_SALT="$(sed -n 's/^ANYRAY_PSEUDONYM_SALT=//p' .env | head -n 1)"
    [ -n "$PSEUDONYM_SALT" ] || PSEUDONYM_SALT="$(hex 32)"

    # The URL developers reach the gateway at — reported to the control plane
    # so the portal can show them the connect URL.
    if [ -z "$GATEWAY_URL" ]; then
      GATEWAY_URL="http://${HOST}:8787"
      # The auto-detected host is often a private/internal address (e.g. an
      # EC2/VPC 172.16–31.x or 10.x, or localhost). That is fine for devs ON the
      # same network, but developers off-VPC (remote, laptops) can't reach it —
      # and it's silently the URL the portal shows them. Flag it so the operator
      # passes --gateway-url with a reachable host (public DNS / VPN address).
      case "$HOST" in
        10.*|192.168.*|127.*|localhost|169.254.* \
          |172.1[6-9].*|172.2[0-9].*|172.3[0-1].*)
          echo "⚠ Gateway URL for developers is http://${HOST}:8787 — a private/internal"
          echo "  address. Devs off this network won't reach it. Re-run with"
          echo "  --gateway-url http://<reachable-host>:8787 (public DNS or VPN address)"
          echo "  to set the URL the portal shows them." ;;
      esac
    fi

    strip_env() { grep -v "^${1}=" .env > .env.tmp || true; mv .env.tmp .env; }
    for k in ANYRAY_METERING_ENABLED ANYRAY_CONTROL_PLANE_URL ANYRAY_DEPLOYMENT_TOKEN \
             ANYRAY_LICENSE_PUBLIC_KEY ANYRAY_DEV_UNSAFE_CONTROL_PLANE ANYRAY_PSEUDONYM_SALT \
             ANYRAY_GATEWAY_PUBLIC_URL ANYRAY_METERING_INTERVAL_MS ANYRAY_ENTITLEMENT_GRACE_MS; do
      strip_env "$k"
    done
    grep -v '^# Anyray Cloud (--connect)' .env > .env.tmp || true; mv .env.tmp .env

    # Common header + connect vars.
    cat >> .env <<EOF
# Anyray Cloud (--connect) — re-run ./setup.sh --connect <token> to reconnect.
ANYRAY_METERING_ENABLED=true
ANYRAY_DEPLOYMENT_TOKEN=${CONNECT_TOKEN}
ANYRAY_PSEUDONYM_SALT=${PSEUDONYM_SALT}
ANYRAY_GATEWAY_PUBLIC_URL=${GATEWAY_URL}
# Explicit values: docker-compose passes unset optional vars as empty strings,
# which gateways before v1.5.1 parse as 0 (metering every tick / zero grace).
ANYRAY_METERING_INTERVAL_MS=900000
ANYRAY_ENTITLEMENT_GRACE_MS=86400000
EOF

    if [ "$CP_NORM" = "$CANONICAL_CP" ]; then
      # Production connect. Newer gateway images PIN the control-plane host and
      # the Ed25519 verify key in the image, so they need neither here. But the
      # published images that customers pull TODAY read both from the
      # environment and SILENTLY skip metering (no log, no phone-home, no
      # billing) if either is missing — so we write the canonical host and the
      # vendor's verify-only key explicitly. This is safe and forward-compatible:
      #   • The host is the canonical vendor host — a pinned image validates it
      #     against its allowlist (passes) and a non-canonical host is REFUSED,
      #     so this never becomes a re-pointable trust knob.
      #   • The key is the vendor's PUBLIC verify-only key (it cannot sign
      #     leases). A pinned image ignores it entirely (an env key is honored
      #     only under ANYRAY_DEV_UNSAFE_CONTROL_PLANE=1, which we do NOT set);
      #     an older image verifies real vendor leases against it.
      # Keep this key in sync with PINNED_LICENSE_PUBLIC_KEY in the gateway's
      # licenseAnchor.ts (same key, distributed two ways).
      cat >> .env <<EOF
ANYRAY_CONTROL_PLANE_URL=${CANONICAL_CP}
ANYRAY_LICENSE_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAOScd41AewtCOmQSkT9N7Jn9V1u+uFykC/Vf8hnfKVPQ=\n-----END PUBLIC KEY-----\n"
EOF
    else
      # Custom control plane → dev/internal builds only. Enable the unsafe
      # override and fetch that control plane's verify key into .env (a stock
      # image ignores both; only a dev build honors them).
      echo "⚠ --control-plane ${CONTROL_PLANE} is not the Anyray control plane (${CANONICAL_CP})."
      echo "  A stock gateway image pins the vendor host + key and will REFUSE to meter against it."
      echo "  Enabling ANYRAY_DEV_UNSAFE_CONTROL_PLANE=1 — honored ONLY by an internal/dev gateway build."
      command -v curl >/dev/null 2>&1 || { echo "✗ curl not found — needed to fetch the dev control plane's verify key" >&2; exit 1; }
      # The verify key is no longer public — it is served only at the admin-gated
      # /admin/license-public-key. A dev operator runs the dev control plane, so
      # they hold its admin token: pass it as ANYRAY_CP_ADMIN_TOKEN. (Or skip the
      # fetch entirely by exporting ANYRAY_LICENSE_PUBLIC_KEY yourself.)
      if [ -z "${ANYRAY_CP_ADMIN_TOKEN:-}" ]; then
        echo "✗ --control-plane needs the dev control plane's admin token to fetch its verify key." >&2
        echo "  Set ANYRAY_CP_ADMIN_TOKEN=… and re-run, or set ANYRAY_LICENSE_PUBLIC_KEY=… yourself." >&2
        exit 1
      fi
      LICENSE_ENDPOINT="${CP_NORM}/admin/license-public-key"
      LICENSE_JSON="$(curl -fsSL --max-time 15 -H "Authorization: Bearer ${ANYRAY_CP_ADMIN_TOKEN}" "$LICENSE_ENDPOINT")" || {
        echo "✗ could not reach ${LICENSE_ENDPOINT} (check the URL, your network, and ANYRAY_CP_ADMIN_TOKEN), then re-run ./setup.sh --connect <token> --control-plane <url>" >&2
        exit 1
      }
      LICENSE_PEM="$(printf '%s' "$LICENSE_JSON" | tr -d '\n\r' | sed -n 's/.*"publicKeyPem"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
      case "$LICENSE_PEM" in
        *"BEGIN PUBLIC KEY"*) : ;;
        *) echo "✗ unexpected response from ${LICENSE_ENDPOINT} (no publicKeyPem) — is ${CONTROL_PLANE} really an Anyray control plane?" >&2; exit 1 ;;
      esac
      cat >> .env <<EOF
# Dev/staging ONLY — overrides the pinned vendor key + host. Never set in prod.
# The URL is written here (not in the common block) because it only takes effect
# under the override; a stock image ignores it and uses the pinned host.
ANYRAY_DEV_UNSAFE_CONTROL_PLANE=1
ANYRAY_CONTROL_PLANE_URL=${CONTROL_PLANE}
ANYRAY_LICENSE_PUBLIC_KEY="${LICENSE_PEM}"
EOF
    fi
    chmod 600 .env

    echo "✓ Connected to Anyray Cloud → .env (metering on; pseudonym salt stays local)"
    echo ""
    echo "  Next:      docker compose up -d"
    echo "  Then:      your deployment will appear as Connected at ${CONTROL_PLANE} within a minute"
    echo "  Gateway:   ${GATEWAY_URL}   (shown to developers in the portal)"
  fi

  # ── Upstream gateway (--upstream) ──────────────────────────────────────────
  # Point Anyray at an existing OpenAI-compatible gateway so clients send plain
  # requests with no x-anyray-config header: the gateway seeds its default
  # routing config from ANYRAY_UPSTREAM_URL on first boot, and the allowlist /
  # trusted-hosts vars clear the SSRF proxy guard for that host. (Re)writes only
  # these three vars — every other line of .env is kept.
  if [ -n "$UPSTREAM_URL" ]; then
    case "$UPSTREAM_URL" in
      http://*|https://*) : ;;
      *) echo "✗ --upstream must be a full URL, e.g. http://host.docker.internal:4000" >&2; exit 1 ;;
    esac

    # Hostname only — no scheme, userinfo, port, or path. The gateway matches the
    # allowlist on URL hostname, so a host:port entry would never match.
    up_rest="${UPSTREAM_URL#*://}"
    up_rest="${up_rest%%/*}"      # strip /path
    up_rest="${up_rest##*@}"      # strip user:pass@
    UP_HOST="${up_rest%%:*}"      # strip :port
    [ -n "$UP_HOST" ] || { echo "✗ could not parse a hostname from --upstream ${UPSTREAM_URL}" >&2; exit 1; }

    is_internal_host() {
      case "$1" in
        localhost|127.*|::1|host.docker.internal|10.*|192.168.* \
          |172.1[6-9].*|172.2[0-9].*|172.3[0-1].*|*.internal|*.local|*.corp) return 0 ;;
        *) return 1 ;;
      esac
    }

    for k in ANYRAY_UPSTREAM_URL ANYRAY_CUSTOM_HOST_ALLOWLIST TRUSTED_CUSTOM_HOSTS; do
      grep -v "^${k}=" .env > .env.tmp 2>/dev/null || true; mv .env.tmp .env
    done
    grep -v '^# Anyray upstream (--upstream)' .env > .env.tmp || true; mv .env.tmp .env

    {
      echo "# Anyray upstream (--upstream) — re-run ./setup.sh --upstream <url> to change."
      echo "ANYRAY_UPSTREAM_URL=${UPSTREAM_URL}"
      echo "ANYRAY_CUSTOM_HOST_ALLOWLIST=${UP_HOST}"
      if is_internal_host "$UP_HOST"; then
        # Gateway defaults to these when TRUSTED_CUSTOM_HOSTS is unset; setting it
        # replaces that set, so re-list the defaults and add the upstream host.
        trusted="localhost,127.0.0.1,::1,host.docker.internal"
        case ",${trusted}," in
          *",${UP_HOST},"*) : ;;
          *) trusted="${trusted},${UP_HOST}" ;;
        esac
        echo "TRUSTED_CUSTOM_HOSTS=${trusted}"
      fi
    } >> .env
    chmod 600 .env

    echo "✓ Upstream set → ${UPSTREAM_URL}  (clients need no x-anyray-config header)"
    is_internal_host "$UP_HOST" && echo "  Proxy guard cleared for internal host ${UP_HOST}"
    [ -n "$CONNECT_TOKEN" ] || { echo ""; echo "  Next:      docker compose up -d"; }
  fi
  exit 0
fi

# ── Kubernetes / Helm mode (--k8s) ───────────────────────────────────────────
# --connect <token> works here too: the deployment token + a locally-generated
# pseudonym salt are folded into anyray-secrets.yaml, and gateway.metering.enabled
# is turned on in my-values.yaml. The control-plane host and the vendor verify key
# stay PINNED in the gateway image — never written here.
if [ -n "$CONNECT_TOKEN" ]; then
  case "$CONNECT_TOKEN" in
    adt_*) : ;;
    *) echo "⚠ deployment token does not start with adt_ — double-check it against app.anyray.ai" ;;
  esac
fi

if [ -f anyray-secrets.yaml ]; then
  echo "✓ anyray-secrets.yaml already exists — leaving it untouched (delete it to regenerate)"
  if [ -n "$CONNECT_TOKEN" ]; then
    echo "  To connect this existing Secret, add these two keys under data: in"
    echo "  anyray-secrets.yaml and set gateway.metering.enabled: true in my-values.yaml:"
    echo "    ANYRAY_DEPLOYMENT_TOKEN: $(b64enc "$CONNECT_TOKEN")"
    echo "    ANYRAY_PSEUDONYM_SALT: $(b64enc "$(hex 32)")"
  fi
  exit 0
fi

ADMIN_TOKEN="ar-adm-$(hex 16)"
LF_PUBLIC_KEY="pk-lf-$(hex 16)"
LF_SECRET_KEY="sk-lf-$(hex 16)"
OPTIMIZER_TOKEN="$(hex 32)"
CONTENT_KEY="$(hex 32)"
NEXTAUTH_SECRET_VAL="$(b64)"
SALT_VAL="$(b64)"
ENCRYPTION_KEY_VAL="$(hex 32)"
POSTGRES_PW="$(hex 16)"
CLICKHOUSE_PW="$(hex 16)"
REDIS_PW="$(hex 16)"
MINIO_PW="$(hex 16)"
INIT_USER_PW="$(hex 16)"

cat > anyray-secrets.yaml <<EOF
# Generated by setup.sh --k8s — do not commit. Delete and re-run to rotate.
apiVersion: v1
kind: Secret
metadata:
  name: anyray-secrets
type: Opaque
data:
  ANYRAY_ADMIN_TOKEN: $(b64enc "$ADMIN_TOKEN")
  ANYRAY_OBSERVABILITY_PUBLIC_KEY: $(b64enc "$LF_PUBLIC_KEY")
  ANYRAY_OBSERVABILITY_SECRET_KEY: $(b64enc "$LF_SECRET_KEY")
  ANYRAY_OPTIMIZER_TOKEN: $(b64enc "$OPTIMIZER_TOKEN")
  ANYRAY_CONTENT_KEY: $(b64enc "$CONTENT_KEY")
  NEXTAUTH_SECRET: $(b64enc "$NEXTAUTH_SECRET_VAL")
  SALT: $(b64enc "$SALT_VAL")
  ENCRYPTION_KEY: $(b64enc "$ENCRYPTION_KEY_VAL")
  ANYRAY_INIT_USER_PASSWORD: $(b64enc "$INIT_USER_PW")
  POSTGRES_PASSWORD: $(b64enc "$POSTGRES_PW")
  CLICKHOUSE_PASSWORD: $(b64enc "$CLICKHOUSE_PW")
  REDIS_AUTH: $(b64enc "$REDIS_PW")
  MINIO_ROOT_PASSWORD: $(b64enc "$MINIO_PW")
EOF

# Anyray Cloud connect (--connect): fold the deployment token + a locally-generated
# pseudonym salt into the Secret. The salt NEVER leaves your cluster — it
# pseudonymizes employee identifiers before the content-free usage rollup. The
# gateway reads these only when gateway.metering.enabled is set (below).
if [ -n "$CONNECT_TOKEN" ]; then
  PSEUDONYM_SALT="$(hex 32)"
  cat >> anyray-secrets.yaml <<EOF
  ANYRAY_DEPLOYMENT_TOKEN: $(b64enc "$CONNECT_TOKEN")
  ANYRAY_PSEUDONYM_SALT: $(b64enc "$PSEUDONYM_SALT")
EOF
fi
chmod 600 anyray-secrets.yaml

echo "✓ Secrets generated → anyray-secrets.yaml"
[ -n "$CONNECT_TOKEN" ] && echo "  ✓ Anyray Cloud connect vars folded in (deployment token + pseudonym salt)"

if [ -f my-values.yaml ]; then
  echo "✓ my-values.yaml already exists — leaving it untouched"
  [ -n "$CONNECT_TOKEN" ] && echo "  To meter, set gateway.metering.enabled: true in my-values.yaml"
else
  {
    echo "# Anyray Helm values — safe to commit (no secrets here)."
    echo "host: \"${HOST}\""
    echo ""
    echo "image:"
    echo "  tag: \"v1.10.2\""
    if [ -n "$CONNECT_TOKEN" ]; then
      echo ""
      echo "# Anyray Cloud metering — deployment token + pseudonym salt live in anyray-secrets.yaml."
      echo "gateway:"
      echo "  metering:"
      echo "    enabled: true"
    fi
  } > my-values.yaml
  echo "✓ Helm values stub → my-values.yaml"
fi
echo ""
echo "  Next:"
echo "    kubectl apply -f anyray-secrets.yaml"
echo "    helm install anyray ./helm -f my-values.yaml"
echo ""
echo "  Admin key: ${ADMIN_TOKEN}   (base64-encoded in anyray-secrets.yaml)"
echo "  Console:   http://${HOST}:3000  (after pods are ready)"
echo "  Gateway:   http://${HOST}:8787"
[ -n "$CONNECT_TOKEN" ] && echo "  Then:      this deployment appears as Connected at ${CONTROL_PLANE} within a minute"
