#!/usr/bin/env bash
# Anyray setup — generates every secret the stack needs.
# Default: writes .env for docker compose.
# With --k8s: writes anyray-secrets.yaml + my-values.yaml for Helm.
# Idempotent: never overwrites existing output files. Flags: --host <h> --k8s.
set -euo pipefail

HOST=""
K8S=0
while [ $# -gt 0 ]; do
  case "$1" in
    --host) HOST="${2:?--host needs a value}"; shift 2 ;;
    --k8s)  K8S=1; shift ;;
    *) echo "✗ unknown flag: $1 (supported: --host <hostname-or-ip> --k8s)" >&2; exit 1 ;;
  esac
done

command -v openssl >/dev/null 2>&1 || { echo "✗ openssl not found" >&2; exit 1; }

if [ "$K8S" -eq 0 ]; then
  command -v docker >/dev/null 2>&1 || { echo "✗ docker not found — https://docs.docker.com/engine/install/" >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { echo "✗ docker compose v2 not found — https://docs.docker.com/compose/install/" >&2; exit 1; }
fi

if [ -z "$HOST" ]; then
  HOST="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  [ -n "$HOST" ] || HOST=localhost
fi

hex() { openssl rand -hex "$1"; }
b64() { openssl rand -base64 32; }
b64enc() { printf '%s' "$1" | base64 | tr -d '\n'; }

# ── Docker Compose mode ──────────────────────────────────────────────────────
if [ "$K8S" -eq 0 ]; then
  if [ -f .env ]; then
    echo "✓ .env already exists — leaving it untouched (delete it to regenerate)"
    grep '^# Console:' .env | sed 's/^# //' || true
    exit 0
  fi

  if [ -z "${DOCKER_HOST:-}" ] && command -v lsof >/dev/null 2>&1; then
    for p in 3000 8787; do
      if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
        echo "⚠ port $p is already in use on this machine — the stack may fail to start"
      fi
    done
  fi

  ADMIN_TOKEN="ar-adm-$(hex 16)"
  LF_PUBLIC_KEY="pk-lf-$(hex 16)"
  LF_SECRET_KEY="sk-lf-$(hex 16)"

  cat > .env <<EOF
# Generated by setup.sh — do not commit. Delete this file and re-run to rotate.
# Console: http://${HOST}:3000

# Gateway ↔ observability (the two pairs must match)
ANYRAY_OBSERVABILITY_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_OBSERVABILITY_SECRET_KEY=${LF_SECRET_KEY}
ANYRAY_INIT_PROJECT_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_INIT_PROJECT_SECRET_KEY=${LF_SECRET_KEY}

# Gateway ↔ optimizer shared secret
ANYRAY_OPTIMIZER_TOKEN=$(hex 32)

# Content privacy (AES-256-GCM at rest; encrypted is the default mode)
ANYRAY_CONTENT_KEY=$(hex 32)
ANYRAY_CONTENT_MODE=encrypted
ANYRAY_ALLOW_PLAINTEXT=false

# Single admin key — gates the console and all /admin APIs
ANYRAY_ADMIN_TOKEN=${ADMIN_TOKEN}

# Observability backend
NEXTAUTH_SECRET=$(b64)
SALT=$(b64)
ENCRYPTION_KEY=$(hex 32)
NEXTAUTH_URL=http://${HOST}:3000
TELEMETRY_ENABLED=false
ANYRAY_INIT_ORG_ID=anyray
ANYRAY_INIT_ORG_NAME=Anyray
ANYRAY_INIT_PROJECT_ID=anyray-gateway
ANYRAY_INIT_PROJECT_NAME=Anyray Gateway
ANYRAY_INIT_USER_EMAIL=admin@anyray.local
ANYRAY_INIT_USER_NAME=Admin
ANYRAY_INIT_USER_PASSWORD=$(hex 16)

# Datastores
POSTGRES_PASSWORD=$(hex 16)
CLICKHOUSE_PASSWORD=$(hex 16)
REDIS_AUTH=$(hex 16)
MINIO_ROOT_PASSWORD=$(hex 16)
EOF
  chmod 600 .env

  echo "✓ Secrets generated → .env"
  echo ""
  echo "  Next:      docker compose up -d"
  echo "  Console:   http://${HOST}:3000"
  echo "  Admin key: ${ADMIN_TOKEN}   (also stored in .env as ANYRAY_ADMIN_TOKEN)"
  echo "  Gateway:   http://${HOST}:8787"
  exit 0
fi

# ── Kubernetes / Helm mode (--k8s) ───────────────────────────────────────────
if [ -f anyray-secrets.yaml ]; then
  echo "✓ anyray-secrets.yaml already exists — leaving it untouched (delete it to regenerate)"
  exit 0
fi

ADMIN_TOKEN="ar-adm-$(hex 16)"
LF_PUBLIC_KEY="pk-lf-$(hex 16)"
LF_SECRET_KEY="sk-lf-$(hex 16)"
OPTIMIZER_TOKEN="$(hex 32)"
CONTENT_KEY="$(hex 32)"
NEXTAUTH_SECRET_VAL="$(b64)"
SALT_VAL="$(b64)"
ENCRYPTION_KEY_VAL="$(hex 32)"
POSTGRES_PW="$(hex 16)"
CLICKHOUSE_PW="$(hex 16)"
REDIS_PW="$(hex 16)"
MINIO_PW="$(hex 16)"
INIT_USER_PW="$(hex 16)"

cat > anyray-secrets.yaml <<EOF
# Generated by setup.sh --k8s — do not commit. Delete and re-run to rotate.
apiVersion: v1
kind: Secret
metadata:
  name: anyray-secrets
type: Opaque
data:
  ANYRAY_ADMIN_TOKEN: $(b64enc "$ADMIN_TOKEN")
  ANYRAY_OBSERVABILITY_PUBLIC_KEY: $(b64enc "$LF_PUBLIC_KEY")
  ANYRAY_OBSERVABILITY_SECRET_KEY: $(b64enc "$LF_SECRET_KEY")
  ANYRAY_OPTIMIZER_TOKEN: $(b64enc "$OPTIMIZER_TOKEN")
  ANYRAY_CONTENT_KEY: $(b64enc "$CONTENT_KEY")
  NEXTAUTH_SECRET: $(b64enc "$NEXTAUTH_SECRET_VAL")
  SALT: $(b64enc "$SALT_VAL")
  ENCRYPTION_KEY: $(b64enc "$ENCRYPTION_KEY_VAL")
  ANYRAY_INIT_USER_PASSWORD: $(b64enc "$INIT_USER_PW")
  POSTGRES_PASSWORD: $(b64enc "$POSTGRES_PW")
  CLICKHOUSE_PASSWORD: $(b64enc "$CLICKHOUSE_PW")
  REDIS_AUTH: $(b64enc "$REDIS_PW")
  MINIO_ROOT_PASSWORD: $(b64enc "$MINIO_PW")
EOF
chmod 600 anyray-secrets.yaml

cat > my-values.yaml <<EOF
# Anyray Helm values — safe to commit (no secrets here).
host: "${HOST}"

image:
  tag: "v0.1.0"
EOF

echo "✓ Secrets generated → anyray-secrets.yaml"
echo "✓ Helm values stub → my-values.yaml"
echo ""
echo "  Next:"
echo "    kubectl apply -f anyray-secrets.yaml"
echo "    helm install anyray ./helm -f my-values.yaml"
echo ""
echo "  Admin key: ${ADMIN_TOKEN}   (base64-encoded in anyray-secrets.yaml)"
echo "  Console:   http://${HOST}:3000  (after pods are ready)"
echo "  Gateway:   http://${HOST}:8787"
