#!/usr/bin/env bash
# Anyray setup — generates every secret the stack needs into .env.
# Idempotent: never overwrites an existing .env. Flags: --host <hostname-or-ip>.
set -euo pipefail

HOST=""
while [ $# -gt 0 ]; do
  case "$1" in
    --host) HOST="${2:?--host needs a value}"; shift 2 ;;
    *) echo "✗ unknown flag: $1 (supported: --host <hostname-or-ip>)" >&2; exit 1 ;;
  esac
done

command -v docker >/dev/null 2>&1 || { echo "✗ docker not found — https://docs.docker.com/engine/install/" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "✗ docker compose v2 not found — https://docs.docker.com/compose/install/" >&2; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "✗ openssl not found" >&2; exit 1; }

if [ -f .env ]; then
  echo "✓ .env already exists — leaving it untouched (delete it to regenerate)"
  grep '^# Console:' .env | sed 's/^# //' || true
  exit 0
fi

if [ -z "$HOST" ]; then
  # Linux: first address of `hostname -I`; macOS/fallback: localhost.
  HOST="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  [ -n "$HOST" ] || HOST=localhost
fi

if [ -z "${DOCKER_HOST:-}" ] && command -v lsof >/dev/null 2>&1; then
  for p in 3000 8787; do
    if lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "⚠ port $p is already in use on this machine — the stack may fail to start"
    fi
  done
fi

hex() { openssl rand -hex "$1"; }
b64() { openssl rand -base64 32; }

ADMIN_TOKEN="ar-adm-$(hex 16)"
LF_PUBLIC_KEY="pk-lf-$(hex 16)"
LF_SECRET_KEY="sk-lf-$(hex 16)"

cat > .env <<EOF
# Generated by setup.sh — do not commit. Delete this file and re-run to rotate.
# Console: http://${HOST}:3000

# Gateway ↔ observability (the two pairs must match)
ANYRAY_OBSERVABILITY_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_OBSERVABILITY_SECRET_KEY=${LF_SECRET_KEY}
ANYRAY_INIT_PROJECT_PUBLIC_KEY=${LF_PUBLIC_KEY}
ANYRAY_INIT_PROJECT_SECRET_KEY=${LF_SECRET_KEY}

# Gateway ↔ optimizer shared secret
ANYRAY_OPTIMIZER_TOKEN=$(hex 32)

# Content privacy (AES-256-GCM at rest; encrypted is the default mode)
ANYRAY_CONTENT_KEY=$(hex 32)
ANYRAY_CONTENT_MODE=encrypted
ANYRAY_ALLOW_PLAINTEXT=false

# Single admin key — gates the console and all /admin APIs
ANYRAY_ADMIN_TOKEN=${ADMIN_TOKEN}

# Observability backend
NEXTAUTH_SECRET=$(b64)
SALT=$(b64)
ENCRYPTION_KEY=$(hex 32)
NEXTAUTH_URL=http://${HOST}:3000
TELEMETRY_ENABLED=false
ANYRAY_INIT_ORG_ID=anyray
ANYRAY_INIT_ORG_NAME=Anyray
ANYRAY_INIT_PROJECT_ID=anyray-gateway
ANYRAY_INIT_PROJECT_NAME=Anyray Gateway
ANYRAY_INIT_USER_EMAIL=admin@anyray.local
ANYRAY_INIT_USER_NAME=Admin
ANYRAY_INIT_USER_PASSWORD=$(hex 16)

# Datastores
POSTGRES_PASSWORD=$(hex 16)
CLICKHOUSE_PASSWORD=$(hex 16)
REDIS_AUTH=$(hex 16)
MINIO_ROOT_PASSWORD=$(hex 16)
EOF
chmod 600 .env

echo "✓ Secrets generated → .env"
echo ""
echo "  Next:      docker compose up -d"
echo "  Console:   http://${HOST}:3000"
echo "  Admin key: ${ADMIN_TOKEN}   (also stored in .env as ANYRAY_ADMIN_TOKEN)"
echo "  Gateway:   http://${HOST}:8787"
