apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anyray.fullname" . }}-worker
  labels:
    {{- include "anyray.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "anyray.selectorLabels" (dict "component" "worker" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "anyray.selectorLabels" (dict "component" "worker" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: worker
          image: docker.io/langfuse/langfuse-worker:3
          env:
            - name: NEXTAUTH_URL
              value: "http://{{ include "anyray.fullname" . }}-web:3000"
            - name: DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@{{ include "anyray.fullname" . }}-postgres:5432/postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "POSTGRES_PASSWORD" "context" .) | nindent 16 }}
            - name: SALT
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "SALT" "context" .) | nindent 16 }}
            - name: ENCRYPTION_KEY
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "ENCRYPTION_KEY" "context" .) | nindent 16 }}
            - name: TELEMETRY_ENABLED
              value: "false"
            - name: CLICKHOUSE_MIGRATION_URL
              value: "clickhouse://{{ include "anyray.fullname" . }}-clickhouse:9000"
            - name: CLICKHOUSE_URL
              value: "http://{{ include "anyray.fullname" . }}-clickhouse:8123"
            - name: CLICKHOUSE_USER
              value: clickhouse
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "CLICKHOUSE_PASSWORD" "context" .) | nindent 16 }}
            - name: CLICKHOUSE_CLUSTER_ENABLED
              value: "false"
            - name: LANGFUSE_S3_EVENT_UPLOAD_BUCKET
              value: langfuse
            - name: LANGFUSE_S3_EVENT_UPLOAD_REGION
              value: auto
            - name: LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID
              value: minio
            - name: LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "MINIO_ROOT_PASSWORD" "context" .) | nindent 16 }}
            - name: LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT
              value: "http://{{ include "anyray.fullname" . }}-minio:9000"
            - name: LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE
              value: "true"
            - name: LANGFUSE_S3_EVENT_UPLOAD_PREFIX
              value: events/
            - name: LANGFUSE_S3_MEDIA_UPLOAD_BUCKET
              value: langfuse
            - name: LANGFUSE_S3_MEDIA_UPLOAD_REGION
              value: auto
            - name: LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID
              value: minio
            - name: LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "MINIO_ROOT_PASSWORD" "context" .) | nindent 16 }}
            - name: LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT
              value: "http://{{ include "anyray.fullname" . }}-minio:9000"
            - name: LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE
              value: "true"
            - name: LANGFUSE_S3_MEDIA_UPLOAD_PREFIX
              value: media/
            - name: REDIS_HOST
              value: "{{ include "anyray.fullname" . }}-redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_AUTH
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "REDIS_AUTH" "context" .) | nindent 16 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
