apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anyray.fullname" . }}-worker
  labels:
    {{- include "anyray.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "anyray.selectorLabels" (dict "component" "worker" "context" .) | nindent 6 }}
  template:
    metadata:
      {{- include "anyray.podMetadata" (dict "component" "worker" "context" .) | nindent 6 }}
    spec:
      {{- include "anyray.podSpecCommon" . | nindent 6 }}
      containers:
        - name: worker
          image: {{ include "anyray.image" (dict "component" "worker" "context" .) }}
          imagePullPolicy: {{ include "anyray.imagePullPolicy" (dict "component" "worker" "context" .) }}
          {{- include "anyray.containerSecurityContext" . | nindent 10 }}
          env:
            - name: NEXTAUTH_URL
              value: "http://web:3000"
            {{- include "anyray.postgresEnv" . | nindent 12 }}
            - name: SALT
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "SALT" "context" .) | nindent 16 }}
            - name: ENCRYPTION_KEY
              valueFrom:
                {{- include "anyray.secretRef" (dict "key" "ENCRYPTION_KEY" "context" .) | nindent 16 }}
            - name: TELEMETRY_ENABLED
              value: "false"
            {{- include "anyray.clickhouseEnv" . | nindent 12 }}
            {{- include "anyray.objectStorageEnv" . | nindent 12 }}
            {{- include "anyray.redisEnv" . | nindent 12 }}
            {{- with .Values.worker.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
