#!/usr/bin/env bash
#
# Regenerate the Railway one-click template publish artifacts from the single
# source of truth: railway/railway.template.json.
#
# WHY THIS IS NOT FULLY HEADLESS
# ------------------------------
# Railway's public GraphQL API cannot publish our template from a file:
#   * templatePublish(id, input) takes only category/description/readme/image
#     /demoProjectId/workspaceId -- there is NO serializedConfig field, so the
#     service architecture cannot be supplied inline.
#   * templateGenerate(projectId, environmentId) builds the draft from a LIVE
#     project and DROPS plain-literal variable defaults (e.g. POSTGRES_USER=
#     postgres becomes empty); there is no API to patch those back.
#   * reading a published template's serializedConfig returns "Not Authorized".
# Net: the literal variable defaults can only be restored in the dashboard's
# per-service "Raw Editor". That manual step is the one thing that drifts and
# gets rebuilt from memory each time.
#
# WHAT THIS SCRIPT DOES
# ---------------------
# Turns railway.template.json into deterministic, paste-ready inputs so a
# re-publish is copy-paste, not reconstruction:
#   * railway/.publish/<service>.vars  -- the KEY=VALUE block for each service's
#     Raw Editor (exact, in template order).
#   * railway/.publish/RUNBOOK.md      -- the ordered dashboard procedure, the
#     publish metadata, the README-section requirements, and the cache-busted
#     verify URL.
# Run it after every railway.template.json change, then follow the runbook.
#
# Usage:  railway/build-publish.sh
# Deps:   bash, jq.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tpl="$here/railway.template.json"
out="$here/.publish"
runbook="$out/RUNBOOK.md"

command -v jq >/dev/null || { echo "error: jq is required" >&2; exit 1; }
[ -f "$tpl" ] || { echo "error: $tpl not found" >&2; exit 1; }
jq -e . "$tpl" >/dev/null || { echo "error: $tpl is not valid JSON" >&2; exit 1; }

mkdir -p "$out"
rm -f "$out"/*.vars "$runbook"

display="$(jq -r '.displayName' "$tpl")"
desc="$(jq -r '.description' "$tpl")"
services="$(jq -r '.services[].name' "$tpl")"

# Railway truncates the marketplace description; keep it short.
desc_len=${#desc}
desc_warn=""
[ "$desc_len" -gt 75 ] && desc_warn=" (WARNING: $desc_len chars > 75 -- Railway truncates; shorten it)"

# --- per-service Raw Editor blocks ------------------------------------------
# Skip empty-valued vars: in a Railway *template* an empty value renders as
# "Empty value to be filled by the user" (a required prompt), which breaks the
# one-click "No config required" UX. The empty optional knobs (rate limits,
# verified-dev gate, upstream) behave identically unset or "" at the gateway,
# so they're omitted from the published template rather than prompted for.
#
# CAVEAT (do not set proxy ANYRAY_UPDATER_TOKEN back to ""): the proxy's nginx
# template injects ${ANYRAY_UPDATER_TOKEN} via envsubst, which only substitutes
# vars present in the environment. Stripping it (empty) leaves a literal $... that
# nginx rejects at startup -> the console crash-loops. It is therefore set to a
# (harmless, updater-off) ${{secret()}} so it survives this filter. Once the proxy
# image that bakes an empty ANYRAY_UPDATER_TOKEN default ships to :stable
# (monorepo: observability/ui/Dockerfile), this template var is no longer needed.
for svc in $services; do
  jq -r --arg n "$svc" '
    .services[] | select(.name == $n) | .variables // {}
    | to_entries[] | select(.value != "") | "\(.key)=\(.value)"
  ' "$tpl" > "$out/$svc.vars"
done

# --- light lint: surface images Railway's validator tends to reject ---------
lint="$(jq -r '
  .services[] | .source.image // empty
  | select(test("^docker\\.io/") or test(":latest$"))
' "$tpl")"

# --- runbook -----------------------------------------------------------------
{
  echo "# Railway template publish runbook"
  echo
  echo "_Generated by \`railway/build-publish.sh\` from \`railway.template.json\`._"
  echo "_Do not edit by hand; re-run the script after changing the template._"
  echo
  echo "## Publish metadata"
  echo
  echo "- **Display name:** $display"
  echo "- **Description:** $desc$desc_warn"
  echo "- **Category:** AI / ML"
  echo "- **Verify URL (cache-bust the CDN!):** https://railway.com/deploy/anyray?v=N"
  echo "  (the plain \`/deploy/anyray\` is CDN-cached and shows the OLD render after a publish)"
  echo
  if [ -n "$lint" ]; then
    echo "> ⚠️ **Image lint:** these images may be rejected by Railway's template validator"
    echo "> (strip a \`docker.io/\` prefix; avoid \`:latest\` -- pin a tag):"
    echo '>'
    while IFS= read -r img; do echo ">   - \`$img\`"; done <<< "$lint"
    echo
  fi
  echo "## Services (compose in this order)"
  echo
  echo "> Empty-valued optional knobs are intentionally omitted from each block:"
  echo "> in a Railway template an empty value becomes a required user prompt,"
  echo "> which would break the one-click \"No config required\" experience."
  echo
  for svc in $services; do
    image="$(jq -r --arg n "$svc" '.services[]|select(.name==$n)|.source.image // "(no image / source build)"' "$tpl")"
    hc="$(jq -r --arg n "$svc" '.services[]|select(.name==$n)|.deploy.healthcheckPath // "(none)"' "$tpl")"
    rp="$(jq -r --arg n "$svc" '.services[]|select(.name==$n)|.deploy.restartPolicyType // "(default)"' "$tpl")"
    sc="$(jq -r --arg n "$svc" '.services[]|select(.name==$n)|.deploy.startCommand // "(image default)"' "$tpl")"
    vol="$(jq -r --arg n "$svc" '.services[]|select(.name==$n)|(.volumes // [])|map(.mountPath)|join(", ")' "$tpl")"
    nvars="$(wc -l < "$out/$svc.vars" | tr -d ' ')"
    echo "### $svc"
    echo
    echo "- **Image:** \`$image\`"
    echo "- **Healthcheck:** $hc"
    echo "- **Restart policy:** $rp"
    [ -n "$vol" ] && echo "- **Volume mount:** $vol"
    echo "- **Start command:** \`$sc\`"
    echo "- **Variables ($nvars):** paste \`railway/.publish/$svc.vars\` into the service's **Raw Editor**, then click **Save** (per service -- batching loses unsaved edits if the dashboard disconnects)."
    echo
  done
  echo "## Procedure"
  echo
  echo "1. Workspace **Templates** → open the published \`anyray\` template → **Edit**."
  echo "2. For each service above: set the image, set Healthcheck / Start command /"
  echo "   Restart policy / Volume as listed, open **Variables → Raw Editor**,"
  echo "   \`Cmd+A\` and paste the matching \`.vars\` block, **Update Variables**, then"
  echo "   **Save** the service before moving on."
  echo "3. Set the **publish README** (the dialog field, not this repo's README). It"
  echo "   MUST contain these exact sections or Railway rejects it:"
  echo "   \`# Deploy and Host\`, \`## About Hosting\`, \`## Why Deploy\`,"
  echo "   \`## Common Use Cases\`, \`## Dependencies for\`, \`### Deployment Dependencies\`."
  echo "4. Confirm Display name / Description / Category match **Publish metadata** above."
  echo "5. Click **Update Template** → expect **Success**."
  echo "6. Verify with the cache-busted URL above: confirm the service list, every"
  echo "   image tag, and that no stale variables remain. Railway's plain URL is"
  echo "   CDN-cached -- always append \`?v=N\` (bump N) when checking."
  echo
  echo "## Why the manual step exists"
  echo
  echo "Railway's API has no way to set a template's variable VALUES headlessly"
  echo "(publish input carries no serializedConfig; generate-from-project strips"
  echo "literal defaults; reads are Not Authorized). The Raw Editor paste above is"
  echo "the only place those literals can be restored. This script keeps that paste"
  echo "deterministic so it never has to be rebuilt from memory."
} > "$runbook"

echo "Wrote:"
echo "  $runbook"
for svc in $services; do echo "  $out/$svc.vars"; done
echo
echo "Next: open $runbook and follow it. (.publish/ is gitignored.)"
